### PR TITLE
Fix loop variables for OpenMP with MSVC

### PR DESCRIPTION
**Pull request by jibsen**
Apparently MSVC does not allow declaring variables in OpenMP loops.

### CODE REVIEW

**Comment by jibsen** [comment]
Besides this, the use of getopt in `pngquant.c` is the only issue I had compiling with MSVC.

**Comment by pornel** [comment]
Thanks for the PR!  OpenMP working is a great news.

Do you have any suggestions what could be done for getopt?

Can I consider your contribution licensed under [BSD 2-clause license](https://spdx.org/licenses/BSD-2-Clause.html)?

**Comment by jibsen** [comment]
> Do you have any suggestions what could be done for getopt?

There are a number of getopt clones that work with MSVC, you could include one of these. I also wrote a small getopt-like thing called [parg](https://github.com/jibsen/parg).

> Can I consider your contribution licensed under BSD 2-clause license?

Sure.

**Comment by pornel** [comment]
I see. Thanks!

**Comment by jibsen** [comment]
If you want to see what it would look like with parg, I made a branch with it [here](https://github.com/jibsen/pngquant/tree/use-parg).

I also found a few more MSVC issues in `pngquant.c` (missing C99 features mostly, and one omp for variable that sneaked past me :blush:).

**Pull request merged**
