### PR TITLE
[RFC] libimagequant: Allow building as a shared library on UNIX

### PR DESCRIPTION
**Pull request by dwbuiten**
Makes it a lot easier to call from other languages.

This is kind of messy, and if you prefer I merge it with the DLL generation (and maybe dylib too?), I will do that.

### CODE REVIEW

**Comment by pornel** [comment]
Thanks!

I think having shared lib build is a good idea.

I don't mind DLL build being separate (it's probably easier for Windows users that way)

Could you generate sharedobjs by replacement of OBJ? I'd like to avoid specifying same file twice.

Why `$(subst lib/libimagequant.a,,$(LDFLAGS))`?

**Comment by dwbuiten** [comment]
> Could you generate sharedobjs by replacement of OBJ? I'd like to avoid specifying same file twice.

Do'h. Yes. I have updated the PR to reflect this.

> Why $(subst lib/libimagequant.a,,$(LDFLAGS))?

It seems `configure` always adds the `.a` to `LDFLAGS`, which cannot work shared library linking (since it needs PIC code, which the `.a` is not). I am not sure what you use it for, so maybe you could explain it a bit.

**Comment by pornel** [comment]
> It seems configure always adds the .a to LDFLAGS

Oh, that may be a mistake. It's needed for pngquant binary, but shouldn't be added to flags of the library itself.

**Comment by sergiomb2** [comment]
I will test this, In fedora have a similar thing 
http://pkgs.fedoraproject.org/cgit/pngquant.git/tree/pngquant-2.3.2_fix-Makefile.patch

**Comment by dwbuiten** [comment]
> Oh, that may be a mistake. It's needed for pngquant binary, but shouldn't be added to flags of the library itself.

Looks like it may have been a copy/paste error? PR updated.

**Comment by pornel** [comment]
Looks good. Thanks!

**Comment by sergiomb2** [comment]
Hello I checked it today ! and we have a problem, at least on Fedora, the rpm of libimagequant stops provides correctly libimagequant.so.0() .
I could fix it with : 
http://pkgs.fedoraproject.org/cgit/pngquant.git/plain/pngquant-2.4.0_fix-Makefile.patch

You define : 
SHAREDOBJS with $(subst .o,.lo,$(OBJS))
after you compile SHAREDOBJS  with : 
$(CC) -fPIC $(CFLAGS) -c $(@:.lo=.c) -o $@
and, at last, do SHAREDLIB with : 
$(CC) -shared -o $(SHAREDLIB) $(SHAREDOBJS) $(LDFLAGS)

With this works: 
$(SHAREDLIB): $(OBJS)
$(CC) -shared -Wl,-soname,$(SHAREDLIB).$(SOVER) $(CFLAGS) $(OBJS) -o $(SHAREDLIB).$(SOVER)
ln -fs $(SHAREDLIB).$(SOVER) $(SHAREDLIB)

Also we need do a symbol link of libimagequant.so.0  to libimagequant.so.0  

I will continue my investigation ...

**Comment by dwbuiten** [comment]
@sergiomb2 That should probably be sent as a PR.

**Pull request merged**
