### PR TITLE
create a header file

### PR DESCRIPTION
**Pull request by 7snovic**
I was developing a tool top of this program, and I found that I have to create a new header file to be able to include the program within my tool, so I think that it would be useful to push this PR.

### CODE REVIEW

**Comment by pornel** [comment]
I wonder what is stopping you from using libimagequant API?

pngquant internals are not a stable API and are going to change.

**Comment by 7snovic** [comment]
it's the first time to know that pngquant is not a stable, However I wanted to use pngquant because it's a ready-to-go solution so I don't need to re-invent the wheel.

**Comment by pornel** [comment]
So the not-reinventing-wheel part has been separated into a library, which has a clear stable API.

The pngquant.c file is just a wrapper for the library, and you're hacking the wrapper in an ad-hoc way.

**Comment by 7snovic** [comment]
aha I see, OK I will try to check out the library instead of pngquant.

**Pull request closed without merging**
